### ISSUE TITLE
Public-code maturity checklist

### ISSUE THREAD

**Issue by milovanderlinden** [peterbartels/health-hacker-hub#16]
We want this project to conform to the [Standard for Public Code](https://standard.publiccode.net/). This is a checklist to check how far we match the standard. This is a checklist that will grow along with our progress.

- [X] Code in the open
- [ ] Bundle policy and source code - needs work, requires BPMN software
- [ ] Create reusable and portable code
- [X] Welcome contributions
- [X] Maintain version control
- [ ] Require review of contributions
- [ ] Document your objectives
- [ ] Document your code
- [ ] use plain English
- [ ] Use open standards
- [ ] Use continuous integration - setting up travis
- [ ] Publish with an open license
- [ ] Use a coherent style
- [ ] Pay attention to codebase maturity
